### ISSUE TITLE
OpenSteer

### ISSUE THREAD

**Issue by dlannan** [erosmarcon/three-steer#1]
Well done with the library - love it. 
Just a note on the Steering works, has been published for a very long time with source code.
http://opensteer.sourceforge.net/
Has a brilliant locality / proximity DB in it which I thought yours might have - looks like I'll have to convert it myself :)
Great work though, and your implementation is one of the cleanest Ive seen.

**Comment by erosmarcon** [comment]
Thank you David,
the library i wrote is very basic and suitable for simple projects i was working on.
I’m not very comfortable with C++, but I know about OpenSteer and its ports and there are also many libraries around in different languages and with more advanced features (proximity databases, but also mixing more behaviours , priority, etc..).
Currently I’ m not planning to update this library, but if you want to add some stuff you’re welcome!
Feel free to open pull requests and/or keep me updated if you do something on your own.
