### ISSUE TITLE
Why does this project based on three.js?

### ISSUE THREAD

**Issue by finscn** [erosmarcon/three-steer#2]
"steering behaviors" is an  AI logic.  ThreeJS is an engine for rendering.

In my opinion , "steering behaviors" doesn't need ThreeJS.

ThreeJS should be used in examples for rendering.

Do you use some features of  three.js in logic ?

**Comment by erosmarcon** [comment]
You're absolutely right and there are already many ‘abstract’ implementations of this logic. 
Probably  ‘based on’ is not the proper definition, it is ‘plugged to’ or ’bounded to’ instead. 
The original idea of wrapping was to simplify things if working on a small three.js project as I was doing ,  although I found myself refactoring the logic with a ‘composition over inheritance’ approach in a more complex scenario (maybe I’ll post something about it here soon)
